version: '3'
services:
  kafka-confluent:
    image: kafka-confluent:latest
    container_name: 'kafka-confluent-container'
    hostname: kafka-confluent
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9999:9999
    env_file:
      - kafka.env
  zookeeper:
    image: zk-confluent:latest
    hostname: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_REPLICAS: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_PORT: 2888
      ZOOKEEPER_ELECTION_PORT: 3888
      ZOOKEEPER_SERVER_ID: 1
  schema_registry:
    image: confluentinc/cp-schema-registry
    hostname: schema_registry
    depends_on:
      - zookeeper
      - kafka-confluent
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
  rest-proxy:
    image: confluentinc/cp-kafka-rest:3.3.0
    hostname: rest-proxy
    depends_on:
      - schema_registry
      - zookeeper
      - kafka-confluent
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema_registry:8081
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka-confluent:9092

