version: '3'
services:
  integration_tests:
    image: iris
    command: npm start integration
    depends_on:
      - kafka
      - zookeeper
      - schema-registry
  kafka:
    image: quay.io/parkhubprime/pk-confluent-kafka:3.3.0
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: quay.io/parkhubprime/pk-confluent-zookeeper:3.3.0
    hostname: zookeeper
    environment:
      ZOOKEEPER_REPLICAS: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_PORT: 2888
      ZOOKEEPER_ELECTION_PORT: 3888
      ZOOKEEPER_SERVER_ID: 1
  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
  rest-proxy:
    image: confluentinc/cp-kafka-rest:3.3.0
    hostname: rest-proxy
    depends_on:
      - schema-registry
      - zookeeper
      - kafka
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092

