version: '3'
services: 
  circe-integration-test:
    build: .
    command: ["npm", "start", "test.integration"]
    volumes:
      - ./:/npm-module
    links:
      - kafka
  zookeeper:
    image: quay.io/parkhubprime/pk-ubuntu-zookeeper:0.1.0
    hostname: zookeeper-0
    environment:
      ZK_REPLICAS: 1
      ZK_CLIENT_PORT: 2181
      ZK_SERVER_PORT: 2888
      ZK_ELECTION_PORT: 3888
  kafka:
    image: quay.io/parkhubprime/pk-ubuntu-kafka:0.1.0
    hostname: kafka
    depends_on:
      - zookeeper
    env_file:
      - kafka.env
