// flow-typed signature: 83d7bf47134e573b32003d6c2c239b03
// flow-typed version: <<STUB>>/are-we-flow-yet_v^1.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'are-we-flow-yet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'are-we-flow-yet' {
  declare module.exports: any;
}
