// flow-typed signature: 0bce80b470d0cf641371bbfcc8ffdd8c
// flow-typed version: <<STUB>>/condition-codefresh_v^1.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'condition-codefresh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'condition-codefresh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'condition-codefresh/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'condition-codefresh/dist/index.js' {
  declare module.exports: $Exports<'condition-codefresh/dist/index'>;
}
