// flow-typed signature: 9436e541c9599df8f824db2197015238
// flow-typed version: <<STUB>>/node-rdkafka_v^2.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-rdkafka'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-rdkafka' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-rdkafka/bench/consumer-raw-rdkafka' {
  declare module.exports: any;
}

declare module 'node-rdkafka/bench/consumer-subscribe' {
  declare module.exports: any;
}

declare module 'node-rdkafka/bench/kafka-consumer-stream' {
  declare module.exports: any;
}

declare module 'node-rdkafka/bench/producer-raw-rdkafka' {
  declare module.exports: any;
}

declare module 'node-rdkafka/bench/producer-rdkafka' {
  declare module.exports: any;
}

declare module 'node-rdkafka/e2e/both.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/e2e/consumer.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/e2e/groups.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/e2e/listener' {
  declare module.exports: any;
}

declare module 'node-rdkafka/e2e/producer.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/client' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/error' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/index' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/kafka-consumer-stream' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/kafka-consumer' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/producer-stream' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/producer' {
  declare module.exports: any;
}

declare module 'node-rdkafka/librdkafka' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/binding.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/consumer.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/error.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/index.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/kafka-consumer-stream.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/mock' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/producer-stream.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/producer.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-rdkafka/bench/consumer-raw-rdkafka.js' {
  declare module.exports: $Exports<'node-rdkafka/bench/consumer-raw-rdkafka'>;
}
declare module 'node-rdkafka/bench/consumer-subscribe.js' {
  declare module.exports: $Exports<'node-rdkafka/bench/consumer-subscribe'>;
}
declare module 'node-rdkafka/bench/kafka-consumer-stream.js' {
  declare module.exports: $Exports<'node-rdkafka/bench/kafka-consumer-stream'>;
}
declare module 'node-rdkafka/bench/producer-raw-rdkafka.js' {
  declare module.exports: $Exports<'node-rdkafka/bench/producer-raw-rdkafka'>;
}
declare module 'node-rdkafka/bench/producer-rdkafka.js' {
  declare module.exports: $Exports<'node-rdkafka/bench/producer-rdkafka'>;
}
declare module 'node-rdkafka/e2e/both.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/e2e/both.spec'>;
}
declare module 'node-rdkafka/e2e/consumer.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/e2e/consumer.spec'>;
}
declare module 'node-rdkafka/e2e/groups.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/e2e/groups.spec'>;
}
declare module 'node-rdkafka/e2e/listener.js' {
  declare module.exports: $Exports<'node-rdkafka/e2e/listener'>;
}
declare module 'node-rdkafka/e2e/producer.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/e2e/producer.spec'>;
}
declare module 'node-rdkafka/lib/client.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/client'>;
}
declare module 'node-rdkafka/lib/error.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/error'>;
}
declare module 'node-rdkafka/lib/index.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/index'>;
}
declare module 'node-rdkafka/lib/kafka-consumer-stream.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/kafka-consumer-stream'>;
}
declare module 'node-rdkafka/lib/kafka-consumer.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/kafka-consumer'>;
}
declare module 'node-rdkafka/lib/producer-stream.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/producer-stream'>;
}
declare module 'node-rdkafka/lib/producer.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/producer'>;
}
declare module 'node-rdkafka/librdkafka.js' {
  declare module.exports: $Exports<'node-rdkafka/librdkafka'>;
}
declare module 'node-rdkafka/test/binding.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/binding.spec'>;
}
declare module 'node-rdkafka/test/consumer.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/consumer.spec'>;
}
declare module 'node-rdkafka/test/error.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/error.spec'>;
}
declare module 'node-rdkafka/test/index.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/index.spec'>;
}
declare module 'node-rdkafka/test/kafka-consumer-stream.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/kafka-consumer-stream.spec'>;
}
declare module 'node-rdkafka/test/mock.js' {
  declare module.exports: $Exports<'node-rdkafka/test/mock'>;
}
declare module 'node-rdkafka/test/producer-stream.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/producer-stream.spec'>;
}
declare module 'node-rdkafka/test/producer.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/producer.spec'>;
}
