// flow-typed signature: 82847aed56977faf3fbd2e82d8ab0735
// flow-typed version: <<STUB>>/node-rdkafka_v^2.3.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-rdkafka'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-rdkafka' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-rdkafka/bench/consumer-raw-rdkafka' {
  declare module.exports: any;
}

declare module 'node-rdkafka/bench/consumer-subscribe' {
  declare module.exports: any;
}

declare module 'node-rdkafka/bench/kafka-consumer-stream' {
  declare module.exports: any;
}

declare module 'node-rdkafka/bench/producer-raw-rdkafka' {
  declare module.exports: any;
}

declare module 'node-rdkafka/bench/producer-rdkafka' {
  declare module.exports: any;
}

declare module 'node-rdkafka/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'node-rdkafka/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'node-rdkafka/docs/toolkit/js/toolkit/toolkit.min' {
  declare module.exports: any;
}

declare module 'node-rdkafka/e2e/both.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/e2e/consumer.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/e2e/groups.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/e2e/listener' {
  declare module.exports: any;
}

declare module 'node-rdkafka/e2e/producer.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/client' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/error' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/index' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/kafka-consumer-stream' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/kafka-consumer' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/producer-stream' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/producer' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/topic-partition' {
  declare module.exports: any;
}

declare module 'node-rdkafka/lib/topic' {
  declare module.exports: any;
}

declare module 'node-rdkafka/librdkafka' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/binding.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/consumer.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/error.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/index.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/kafka-consumer-stream.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/mock' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/producer-stream.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/producer.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/test/topic-partition.spec' {
  declare module.exports: any;
}

declare module 'node-rdkafka/util/configure' {
  declare module.exports: any;
}

declare module 'node-rdkafka/util/get-env' {
  declare module.exports: any;
}

declare module 'node-rdkafka/util/test-compile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-rdkafka/bench/consumer-raw-rdkafka.js' {
  declare module.exports: $Exports<'node-rdkafka/bench/consumer-raw-rdkafka'>;
}
declare module 'node-rdkafka/bench/consumer-subscribe.js' {
  declare module.exports: $Exports<'node-rdkafka/bench/consumer-subscribe'>;
}
declare module 'node-rdkafka/bench/kafka-consumer-stream.js' {
  declare module.exports: $Exports<'node-rdkafka/bench/kafka-consumer-stream'>;
}
declare module 'node-rdkafka/bench/producer-raw-rdkafka.js' {
  declare module.exports: $Exports<'node-rdkafka/bench/producer-raw-rdkafka'>;
}
declare module 'node-rdkafka/bench/producer-rdkafka.js' {
  declare module.exports: $Exports<'node-rdkafka/bench/producer-rdkafka'>;
}
declare module 'node-rdkafka/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'node-rdkafka/docs/scripts/prettify/lang-css'>;
}
declare module 'node-rdkafka/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'node-rdkafka/docs/scripts/prettify/prettify'>;
}
declare module 'node-rdkafka/docs/toolkit/js/toolkit/toolkit.min.js' {
  declare module.exports: $Exports<'node-rdkafka/docs/toolkit/js/toolkit/toolkit.min'>;
}
declare module 'node-rdkafka/e2e/both.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/e2e/both.spec'>;
}
declare module 'node-rdkafka/e2e/consumer.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/e2e/consumer.spec'>;
}
declare module 'node-rdkafka/e2e/groups.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/e2e/groups.spec'>;
}
declare module 'node-rdkafka/e2e/listener.js' {
  declare module.exports: $Exports<'node-rdkafka/e2e/listener'>;
}
declare module 'node-rdkafka/e2e/producer.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/e2e/producer.spec'>;
}
declare module 'node-rdkafka/lib/client.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/client'>;
}
declare module 'node-rdkafka/lib/error.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/error'>;
}
declare module 'node-rdkafka/lib/index.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/index'>;
}
declare module 'node-rdkafka/lib/kafka-consumer-stream.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/kafka-consumer-stream'>;
}
declare module 'node-rdkafka/lib/kafka-consumer.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/kafka-consumer'>;
}
declare module 'node-rdkafka/lib/producer-stream.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/producer-stream'>;
}
declare module 'node-rdkafka/lib/producer.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/producer'>;
}
declare module 'node-rdkafka/lib/topic-partition.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/topic-partition'>;
}
declare module 'node-rdkafka/lib/topic.js' {
  declare module.exports: $Exports<'node-rdkafka/lib/topic'>;
}
declare module 'node-rdkafka/librdkafka.js' {
  declare module.exports: $Exports<'node-rdkafka/librdkafka'>;
}
declare module 'node-rdkafka/test/binding.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/binding.spec'>;
}
declare module 'node-rdkafka/test/consumer.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/consumer.spec'>;
}
declare module 'node-rdkafka/test/error.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/error.spec'>;
}
declare module 'node-rdkafka/test/index.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/index.spec'>;
}
declare module 'node-rdkafka/test/kafka-consumer-stream.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/kafka-consumer-stream.spec'>;
}
declare module 'node-rdkafka/test/mock.js' {
  declare module.exports: $Exports<'node-rdkafka/test/mock'>;
}
declare module 'node-rdkafka/test/producer-stream.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/producer-stream.spec'>;
}
declare module 'node-rdkafka/test/producer.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/producer.spec'>;
}
declare module 'node-rdkafka/test/topic-partition.spec.js' {
  declare module.exports: $Exports<'node-rdkafka/test/topic-partition.spec'>;
}
declare module 'node-rdkafka/util/configure.js' {
  declare module.exports: $Exports<'node-rdkafka/util/configure'>;
}
declare module 'node-rdkafka/util/get-env.js' {
  declare module.exports: $Exports<'node-rdkafka/util/get-env'>;
}
declare module 'node-rdkafka/util/test-compile.js' {
  declare module.exports: $Exports<'node-rdkafka/util/test-compile'>;
}
