// flow-typed signature: 50b99923949717a1907a398b7ec8eec9
// flow-typed version: <<STUB>>/nps-utils_v^1.3.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nps-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nps-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nps-utils/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nps-utils/dist/index.js' {
  declare module.exports: $Exports<'nps-utils/dist/index'>;
}
