// flow-typed signature: 96c7c16599a431dd27a80b8517ae2378
// flow-typed version: <<STUB>>/@telerik/semantic-prerelease_v^1.2.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@telerik/semantic-prerelease'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@telerik/semantic-prerelease' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@telerik/semantic-prerelease/analyzeCommits' {
  declare module.exports: any;
}

declare module '@telerik/semantic-prerelease/bin/find-dev-deps' {
  declare module.exports: any;
}

declare module '@telerik/semantic-prerelease/bin/semantic-prerelease' {
  declare module.exports: any;
}

declare module '@telerik/semantic-prerelease/generateNotes' {
  declare module.exports: any;
}

declare module '@telerik/semantic-prerelease/getLastRelease' {
  declare module.exports: any;
}

declare module '@telerik/semantic-prerelease/lastTag' {
  declare module.exports: any;
}

declare module '@telerik/semantic-prerelease/validateConfig' {
  declare module.exports: any;
}

declare module '@telerik/semantic-prerelease/verifyConditions' {
  declare module.exports: any;
}

declare module '@telerik/semantic-prerelease/verifyRelease' {
  declare module.exports: any;
}

// Filename aliases
declare module '@telerik/semantic-prerelease/analyzeCommits.js' {
  declare module.exports: $Exports<'@telerik/semantic-prerelease/analyzeCommits'>;
}
declare module '@telerik/semantic-prerelease/bin/find-dev-deps.js' {
  declare module.exports: $Exports<'@telerik/semantic-prerelease/bin/find-dev-deps'>;
}
declare module '@telerik/semantic-prerelease/bin/semantic-prerelease.js' {
  declare module.exports: $Exports<'@telerik/semantic-prerelease/bin/semantic-prerelease'>;
}
declare module '@telerik/semantic-prerelease/generateNotes.js' {
  declare module.exports: $Exports<'@telerik/semantic-prerelease/generateNotes'>;
}
declare module '@telerik/semantic-prerelease/getLastRelease.js' {
  declare module.exports: $Exports<'@telerik/semantic-prerelease/getLastRelease'>;
}
declare module '@telerik/semantic-prerelease/lastTag.js' {
  declare module.exports: $Exports<'@telerik/semantic-prerelease/lastTag'>;
}
declare module '@telerik/semantic-prerelease/validateConfig.js' {
  declare module.exports: $Exports<'@telerik/semantic-prerelease/validateConfig'>;
}
declare module '@telerik/semantic-prerelease/verifyConditions.js' {
  declare module.exports: $Exports<'@telerik/semantic-prerelease/verifyConditions'>;
}
declare module '@telerik/semantic-prerelease/verifyRelease.js' {
  declare module.exports: $Exports<'@telerik/semantic-prerelease/verifyRelease'>;
}
