// flow-typed signature: 24a982d8582b38d766bd7e4412563fa7
// flow-typed version: <<STUB>>/@parkhub/circe-middleware_v1.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@parkhub/circe-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@parkhub/circe-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@parkhub/circe-middleware/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@parkhub/circe-middleware/dist/index.js' {
  declare module.exports: $Exports<'@parkhub/circe-middleware/dist/index'>;
}
