// flow-typed signature: 0a0d1baaaa03f812706c1471f1733282
// flow-typed version: <<STUB>>/@parkhub/eslint-config-parkhub-base_v^1.2.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@parkhub/eslint-config-parkhub-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@parkhub/eslint-config-parkhub-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@parkhub/eslint-config-parkhub-base/dist/eslintrc' {
  declare module.exports: any;
}

declare module '@parkhub/eslint-config-parkhub-base/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@parkhub/eslint-config-parkhub-base/dist/eslintrc.js' {
  declare module.exports: $Exports<'@parkhub/eslint-config-parkhub-base/dist/eslintrc'>;
}
declare module '@parkhub/eslint-config-parkhub-base/dist/index.js' {
  declare module.exports: $Exports<'@parkhub/eslint-config-parkhub-base/dist/index'>;
}
